

name: CI


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
  workflow_dispatch:


jobs:
 
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v4

      
      - name: Build image
        run: docker build -t robpel1/portfolio .

     
      - name: Push image
        run: |
             docker login -u robpel1 -p ${{secrets.REGISTRY_PASS}}
             docker push robpel1/portfolio
